apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundle2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      containers:
      - image: nginx
        name: bundle2con
